# Generated by Django 5.1 on 2024-10-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dbzkngkda/image/upload/v1724665868/Test/default_post_m1op5w.jpg', upload_to='images/'),
        ),
    ]
