# Generated by Django 5.1 on 2024-09-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dbzkngkda/image/upload/v1724665896/Test/default_profile_hhelfd.jpg', upload_to='images/'),
        ),
    ]
